[package]
name = "wgpu-volume-rendering"
version = "0.1.0"
edition = "2021"

[dependencies]
pollster = "0.4.0"
wgpu = "23.0.0"
winit = "0.30.5"
dicom = "0.8.0"
dicom-dictionary-std = "0.8.0"
anyhow = "1.0"
bytemuck = "1.19.0"
